### ISSUE TITLE
Jwt一直验证401

### ISSUE THREAD

**Issue by lisenz** [WeihanLi/WeihanLi.Web.Extensions#26]
你好，我使用代码中的JWT进行API授权认证处理，以下是我在Startup的配置
![image](https://user-images.githubusercontent.com/18478465/159227015-58e92ba4-cdb2-400f-9798-d6e33fbe4d4d.png)

现在出现的问题是请求的API似乎一直没有验证成功，请求一直都是401，我想请问下是不是哪里还配置少了什么

**Comment by WeihanLi** [comment]
需要调用 `services.AddJwtTokenServiceWithJwtBearerAuth` 这个方法来注册，这个方法会配置 `JwtBearerOptions`，可以参考示例项目
